-- AUTOGENERATED BY storj.io/dbx
-- DO NOT EDIT
CREATE TABLE fruits (
	id integer NOT NULL,
	name varchar(50) NOT NULL,
	color varchar(20) NOT NULL,
	calories_per_100g integer NOT NULL,
	is_tropical boolean NOT NULL,
	PRIMARY KEY ( id )
) ;
CREATE TABLE schema_versions (
	number integer NOT NULL,
	comment text NOT NULL,
	PRIMARY KEY ( number )
)
