version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/amwolff/go-project-template
run:
  timeout: 5m
  modules-download-mode: readonly
